name: ai_fitness_coach
description: Next-generation AI-powered fitness coaching app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core UI
  cupertino_icons: ^1.0.6
  glass_kit: ^4.0.1  # For glassmorphism effects
  blur: ^3.1.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Navigation
  go_router: ^13.0.1
  
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  
  # Authentication
  google_sign_in: ^6.1.6
  crypto: ^3.0.3
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # JSON
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  fl_chart: ^0.66.0
  
  # Utilities
  uuid: ^4.2.2
  intl: ^0.18.1
  permission_handler: ^11.1.0
  
  # Health & Fitness
  health: ^9.0.1
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # Animations
  animations: ^2.0.10
  
  # Icons
  font_awesome_flutter: ^10.6.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Text-to-Speech
  flutter_tts: ^4.0.2
  google_speech: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - .env
